version: "3"

services:
  server:
    build: "./server"
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - default
    environment:
      - PORT=8080
    restart: on-failure

  client:
    build: "./client"
    ports:
      - "8081:8081"
    expose:
      - 8081
    networks:
      - default
    depends_on:
      - server
    environment:
      - PORT=8081
    restart: on-failure
    

networks:
  default:
